# Generated by Django 4.2 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_user_notification_delay_days"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["stable_id"], name="dashboard_o_stable__idx"),
        ),
    ]
