# Generated by Django 4.2.28 on 2026-02-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0020_observation_stable_id_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasisOfRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
