# Generated by Django 4.2.28 on 2026-02-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0021_create_basis_of_record_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="basis_of_record_filters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional (no selection = notify me for all basis of records). To select multiple items, press and hold the Ctrl or Command key and click the items.",
                to="dashboard.basisofrecord",
                verbose_name="basis of record",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="basis_of_record_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.basisofrecord",
            ),
        ),
    ]
